### ISSUE TITLE
tensorflow-2.0.0-cp37-CPU-SSE

### ISSUE THREAD

**Issue by Alpich** [fo40225/tensorflow-windows-wheel#105]
Hi, have some problems with trying to import. Anyone else get it?
Windows 8.1 64bit
Python 3.7.4
![12](https://user-images.githubusercontent.com/56114562/67386973-9c740d80-f59e-11e9-9980-0412772532c0.png)

**Comment by giordyb** [comment]
Same issue with the avx2 version:
windows 10 
python 3.7.4
```
Traceback (most recent call last):
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Impossibile trovare il modulo specificato.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "new_evaluate_3d.py", line 11, in <module>
    from yolo3utils import parse_voc_annotation
  File "c:\users\biagio\documents\mlprojects\yolotrainer\yolo3utils\yolo3utils\__init__.py", line 2, in <module>
    from .yolo import create_yolov3_model, YoloLayer
  File "c:\users\biagio\documents\mlprojects\yolotrainer\yolo3utils\yolo3utils\yolo.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\BIAGIO\AppData\Local\Continuum\anaconda3\envs\yolo-guiapp37-avx2\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Impossibile trovare il modulo specificato.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by fo40225** [comment]
Can't read Cyrillic or Italiano...

What is the problem, DLL file not found or function in dll is missing?

**Comment by giordyb** [comment]
Sorry, forgot to translate that part..after "DLL load failed" it says "cannot find the specified module"

**Comment by fo40225** [comment]
Try to install Microsoft Visual C++ Redistributable for Visual Studio 2019.3

**Comment by Alpich** [comment]
Thx @fo40225. Installation MVC 2019 helped me 
Error was: "DLL load failed. cannot find the specified module"

**Comment by hbyido** [comment]
@Alpich  Hi，I got the same problem，could you provide the link of  MVC 2019？ thank you。

**Comment by hbyido** [comment]
@Alpich  have got it  https://visualstudio.microsoft.com/zh-hans/downloads/?rr=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Fhelp%2F2977003%2Fthe-latest-supported-visual-c-downloads

**Comment by s-afanasiev** [comment]
sorry,
1) I already installed Microsoft Visual C++ Redistributable for Visual Studio 2019.4
2) python 3.7.5
3) trying to setup tensorflow-windows-wheel/2.0.0/py37/CPU/sse2/tensorflow-2.0.0-cp37-cp37m-win_amd64.whl
and got erorr: "is not a supported whhel on this platform" ! Why?
Although, it's OK then i setup, for example, tensorflow-windows-wheel/1.13.1/py37/CPU/sse2/tensorflow-1.13.1-cp37-cp37m-win_amd64.whl

**Comment by xXDarkCubeXx** [comment]
can you go around installing MVS?
