### ISSUE TITLE
tensorflow-windows-wheel/2.0.0/py37/CPU/avx2/tensorflow-2.0.0-cp37-cp37m-win_amd64.whl

### ISSUE THREAD

**Issue by beyond6138** [fo40225/tensorflow-windows-wheel#114]
tensorflow-windows-wheel/2.0.0/py37/CPU/avx2/tensorflow-2.0.0-cp37-cp37m-win_amd64.whl can't install

**Comment by fo40225** [comment]
What is the error message?

**Comment by wing-wuchen** [comment]
@fo40225 
this ia my error log, please check it, thanks


Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "E:\conda\envs\t1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "E:\conda\envs\t1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\conda\envs\t1\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "E:\conda\envs\t1\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "E:\conda\envs\t1\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "E:\conda\envs\t1\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "E:\conda\envs\t1\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "E:\conda\envs\t1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "E:\conda\envs\t1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: 找不到指定的模块。


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by fo40225** [comment]
@wing-wuchen #105

**Comment by wing-wuchen** [comment]
thank you! 
the problem has been done

just need to install "Microsoft Visual C++ Redistributable for Visual Studio 2019.3"

https://visualstudio.microsoft.com/zh-hans/downloads/?rr=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Fhelp%2F2977003%2Fthe-latest-supported-visual-c-downloads

**Comment by chenxijun** [comment]
@wing-wuchen I'm thankful for you issue because it greatly solved a problem which confused me for a long time. But your title is hard to know the actual meaning of your problem.
非常感谢你帮助我解决了这个困扰我许久的问题哈，但是标题实在是太难以表意了，希望能更改一下
