### ISSUE TITLE
tensorflow-windows-wheel / 2.0.0 / py37 / GPU /cuda101cudnn76avx2/

### ISSUE THREAD

**Issue by Zakizengxjie** [fo40225/tensorflow-windows-wheel#115]
## After I installing cuda101cudnn76avx2,my computer reported the following error:

2019-11-22 22:12:50.475457: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2019-11-22 22:12:52.558212: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-11-22 22:12:52.681090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 950M major: 5 minor: 0 memoryClockRate(GHz): 0.928
pciBusID: 0000:01:00.0
2019-11-22 22:12:52.689510: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-22 22:12:52.707460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "j:/1_CodeContent/pywork/tensor2.0/test.py", line 6, in <module>
    gpu_ok = tf.test.is_gpu_available()
  File "J:\Anancond\envs\errov\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1432, in is_gpu_available
    for local_device in device_lib.list_local_devices():
  File "J:\Anancond\envs\errov\lib\site-packages\tensorflow_core\python\client\device_lib.py", line 41, in list_local_devices
    for s in pywrap_tensorflow.list_devices(session_config=session_config)
  File "J:\Anancond\envs\errov\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 2249, in list_devices
    return ListDevices()
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.

**Comment by fo40225** [comment]
You need to have cuda 10.1 installed to use this repo's wheel.

You can use official pip package that supports cuda 10.

**Comment by Zakizengxjie** [comment]
ok,thank you。
