### ISSUE TITLE
AttributeError: 'file' object has no attribute 'readable'

### ISSUE THREAD

**Issue by asxdfd** [fo40225/tensorflow-windows-wheel#119]
I'm compiling tensorflow 1.12.0 for python 2.7.
This is the error:
Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\temp\Bazel.runfiles_zj0qm9\runfiles\local_config_def_file_filter\def_file_filter.py", line 169, in <module>
    sys.exit(main())
  File "c:\users\lenovo\appdata\local\temp\Bazel.runfiles_zj0qm9\runfiles\local_config_def_file_filter\def_file_filter.py", line 130, in main
    for idx, line in enumerate(io.TextIOWrapper(proc.stdout, encoding="utf-8")):
AttributeError: 'file' object has no attribute 'readable'

How can I fix it?

**Comment by fo40225** [comment]
Trying to use cmake, I have never succeeded in building tensorflow with python 2.7 using bazel on windows.

**Comment by asxdfd** [comment]
When I use cmake, some errors occured:
`CMake Error at tf_core_kernels.cmake:221 (add_library):
  Cannot find source file:

    D:/EB/tensorflow-r1.12/tensorflow/core/kernels/data/experimentalassert_next_dataset_op.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:519 (include)


CMake Error at tf_core_ops.cmake:73 (add_library):
  Cannot find source file:

    D:/EB/tensorflow-r1.12/tensorflow/contrib/core/ops/dataset_ops.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  tf_core_ops.cmake:92 (GENERATE_CONTRIB_OP_LIBRARY)
  CMakeLists.txt:517 (include)


CMake Error at tf_core_ops.cmake:73 (add_library):
  No SOURCES given to target: tf_contrib_data_dataset_ops
Call Stack (most recent call first):
  tf_core_ops.cmake:92 (GENERATE_CONTRIB_OP_LIBRARY)
  CMakeLists.txt:517 (include)


CMake Error at tf_core_kernels.cmake:221 (add_library):
  No SOURCES given to target: tf_core_kernels
Call Stack (most recent call first):
  CMakeLists.txt:519 (include)`
I tried to change some paths in tf_core_kernels.cmake and tf_core_ops.cmake, but it didn't work at all. How to fix this?
By the way, this is my environment:
Windows 10
Microsoft Visual Studio 2015
cmake 3.16.0
swigwin 4.0.1
python 2.7(virtual env created by Pycharm)
tensorflow-r1.12

**Comment by fo40225** [comment]
The last tensorflow version I successfully built and work by using cmake was 1.8.
You need to revert https://github.com/tensorflow/tensorflow/pull/19415/files after 1.9, you can build it with revert until 1.10.
After you successfully build 1.10, you can compare the differences between 1.10 and 1.12 and fix them.

**Comment by asxdfd** [comment]
Thanks for your help. Finally I succeed with bazel.
