### ISSUE TITLE
tensorflow-2.1.0-cp37-cp37m-win_amd64.whl - Failed to get convolution algorithm

### ISSUE THREAD

**Issue by astridtijskens** [fo40225/tensorflow-windows-wheel#126]
**System information**

- OS Platform and Distribution: Windows 10
- Python version: 3.7
- CUDA/cuDNN version: 10.2.89_441.22/7.6.5.32
- GPU model and memory: 2x GPU RTX 2080 8.00GiB

I get the following error:

```
2020-02-20 11:45:37.405155: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:37.405239: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:37.409865: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:37.409942: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:37.410083: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node replica_1/model/conv1d/conv1d}}]]
	 [[replica_1/loss/mul/_80]]
2020-02-20 11:45:37.410300: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node replica_1/model/conv1d/conv1d}}]]
	 [[Adam/Adam/update_1_1/AssignAddVariableOp/_103]]
2020-02-20 11:45:37.410567: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node replica_1/model/conv1d/conv1d}}]]
2020-02-20 11:45:37.418858: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:37.418937: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:37.450551: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:37.450630: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:38.459423: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:38.459507: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:38.460223: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:38.460294: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:38.460620: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:38.460694: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:38.461417: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-20 11:45:38.461493: E tensorflow/stream_executor/cuda/cuda_dnn.cc:333] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-02-20 11:45:38.479648: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-02-20 11:45:38.479730: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1259] Profiler found 2 GPUs
2020-02-20 11:45:38.480628: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cupti64_102.dll
WARNING:tensorflow:Early stopping conditioned on metric 'val_loss' which is not available. Available metrics are: 
2020-02-20 11:45:38.885722: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1378] CUPTI activity buffer flushed
2020-02-20 11:45:38.885788: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 5 callback api events and 5 activity events.
Traceback (most recent call last):
  File "C:/Users/Astrid/Documents/Metamodelling/ExtrapolateClimates-2/train_network.py", line 54, in <module>
    callbacks=[earlyStopping, TensorBoard(log_dir='.\\logs', write_graph=False, profile_batch=2)])
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\eager\function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
    ctx=ctx)
  File "C:\ProgramData\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node replica_1/model/conv1d/conv1d (defined at \threading.py:926) ]]
	 [[replica_1/loss/mul/_80]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node replica_1/model/conv1d/conv1d (defined at \threading.py:926) ]]
0 successful operations.
1 derived errors ignored. [Op:__inference_distributed_function_27180]

Function call stack:
distributed_function -> distributed_function

2020-02-20 11:45:39.114739: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-02-20 11:45:39.115551: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
```
 I already tried adding fixes involving

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
```
but none of them work.
How to solve this issue?

**Comment by fo40225** [comment]
Have you tried rebooting?

Check your driver's version, you can install the latest driver.

**Comment by astridtijskens** [comment]
Yeah, I rebooted and I have the latest driver 442.19.

I think maybe Tensorflow 2.1 doesn't support CUDA 10.2? I now installed  TF2.1 build from source for CUDA 10.1/CuDNN 7.6.5 and there I have no problem.

**Comment by fo40225** [comment]
You can try to use the driver 441.22 which bundled with CUDA 10.2, maybe the game driver and cuda driver are different.

If there is still a problem, it may be a bug in windows / cuda / cudnn / tensorflow.

**Comment by astridtijskens** [comment]
I have a working version of TF2.1 now (CUDA 1.1). I am sorry, but I don't have time to reinstall everything to test this.
Feel free to close.
