### ISSUE TITLE
Error installing 1.8.0\py36\GPU\cuda91cudnn71avx2

### ISSUE THREAD

**Issue by elranu** [fo40225/tensorflow-windows-wheel#13]
hello Great repo, thanks!

But I'm getting the following error when I try to install on windows 10 x64:
```
pip install --ignore-installed --upgrade "https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.8.0/py36/GPU/cuda91cudnn71avx2/tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl"
Collecting tensorflow-gpu==1.8.0 from https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.8.0/py36/GPU/cuda91cudnn71avx2/tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl
  Downloading https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.8.0/py36/GPU/cuda91cudnn71avx2/tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl
     / 40kB 239kB/s
Exception:
Traceback (most recent call last):
  File "c:\dev\python36\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\dev\python36\lib\site-packages\pip\_internal\commands\install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "c:\dev\python36\lib\site-packages\pip\_internal\resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\dev\python36\lib\site-packages\pip\_internal\resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\dev\python36\lib\site-packages\pip\_internal\resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "c:\dev\python36\lib\site-packages\pip\_internal\operations\prepare.py", line 310, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\dev\python36\lib\site-packages\pip\_internal\download.py", line 837, in unpack_url
    progress_bar=progress_bar
  File "c:\dev\python36\lib\site-packages\pip\_internal\download.py", line 678, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\dev\python36\lib\site-packages\pip\_internal\utils\misc.py", line 575, in unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\dev\python36\lib\site-packages\pip\_internal\utils\misc.py", line 460, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "c:\dev\python36\lib\zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "c:\dev\python36\lib\zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Any idea how to solve it? Thanks!

**Comment by fo40225** [comment]
@elranu try to download the whl file to local, it seems like a network connection problem.

**Comment by LSinev** [comment]
Wrong link maybe. I think correct is https://github.com/fo40225/tensorflow-windows-wheel/raw/master/1.8.0/py36/GPU/cuda91cudnn71avx2/tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64.whl (not `blob/...`)

**Comment by elranu** [comment]
@LSinev thanks! yes it was blob instead of raw. Thanks
