### ISSUE TITLE
Home Assistant and Windows Tensorflow

### ISSUE THREAD

**Issue by StefanoGiu** [fo40225/tensorflow-windows-wheel#137]
Hello, I have HA running on Windows 10 and I want to test Tensorflow integration. I came to this because of the "DLL load failed with error code".

I tried to install tensorflow 2.2.0 but I got the following error:

2020-04-21 12:38:56 ERROR (MainThread) [homeassistant.components.image_processing] Error while setting up tensorflow platform for image_processing
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "C:\Python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python38\lib\site-packages\homeassistant\components\tensorflow\image_processing.py", line 118, in setup_platform
    od_graph_def = tf.GraphDef()
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

So I decided to install 1.13.1 or 1.14... but when I try it, I got:
ERROR: tensorflow-1.14.0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

I'm running with Python 3.8.

What shall I do?

**Comment by fo40225** [comment]
https://github.com/fo40225/tensorflow-windows-wheel/issues/105#issuecomment-545907707

**Comment by StefanoGiu** [comment]
Could you please explain? Shall I stay on 2.2 and just install MVC ?

**Comment by StefanoGiu** [comment]
Pls read my comment, I think my issue is different here... I was able to install 2.2.0...

**Comment by StefanoGiu** [comment]
I installed MVC 2019 and still I get the following (with 2.1.0)

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "C:\Python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python38\lib\site-packages\homeassistant\components\tensorflow\image_processing.py", line 118, in setup_platform
    od_graph_def = tf.GraphDef()
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

**Comment by fo40225** [comment]
Please check your code is compatible with tf 2.0.

**Comment by StefanoGiu** [comment]
I'm using Home Assistant integration and I don't think it's compatible with TF 2.0.

Is it possible to install 1.13.1 with Python 3.8?

**Comment by StefanoGiu** [comment]
I'm on Windows 10... and Python 3.8. So there's no support?

Home assistant is not working with Tensor Flow 2.X

**Comment by hetul-patel** [comment]
You can try importing tensorflow like this
import tensorflow as tfv2
tf = tfv2.compat.v1

Tensorflow 2.x supports tensorflow 1.x code through tensorflow.compat.v1 module.

**Comment by cyberluke** [comment]
Tensorflow supports only Python 3.7, not 3.8
