### ISSUE TITLE
How to build tensorflow from source

### ISSUE THREAD

**Issue by yanhaiming56** [fo40225/tensorflow-windows-wheel#50]
Can you give the full tutorial about how to build tensorflow from source based on windows system ?

**Comment by fo40225** [comment]
https://www.tensorflow.org/install/source_windows

**Comment by yanhaiming56** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\include\yvals_core.h(298): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.15 or newer

When I use "msys2, bazel, visual studio 2017, win10 " compile the tensorflow source(master branch), it get the error. How do I resolute it?

**Comment by yanhaiming56** [comment]
> https://www.tensorflow.org/install/source_windows

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\include\yvals_core.h(298): fatal error C1189: #error: STL1001: Unexpected compiler version, expected MSVC 19.15 or newer

When I use "msys2, bazel, visual studio 2017, win10 " compile the tensorflow source(master branch), it get the error. How do I resolute it?

**Comment by fo40225** [comment]
- use stable branch (r1.x)
- install msys2 only, command should type in cmd.exe not bash
- check your msvc installation, your msvc header is 15.8 and cl.exe should match it

**Comment by juliusfrost** [comment]
`C:\Users\Julius\Downloads\tensorflow>bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: C:/users/julius/_bazel_julius/stzd376a/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/julius/_bazel_julius/stzd376a/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables, eg. VS140COMNTOOLS
DEBUG: C:/users/julius/_bazel_julius/stzd376a/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1303, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 153, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1447
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1303, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(repository_ctx)
        File "C:/users/julius/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 153, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
type 'NoneType' has no method replace(string, string)
INFO: Elapsed time: 1.037s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package`

**Comment by fo40225** [comment]
@juliusfrost `SET PATH=C:\msys64\usr\bin;%PATH%`

**Comment by juliusfrost** [comment]
I already did that, it still gets the same error

**Comment by fo40225** [comment]
@juliusfrost What is your bazel version? Use bazel 0.15.0 exactly.

**Comment by juliusfrost** [comment]
I did that too actually

**Comment by fo40225** [comment]
@juliusfrost Sorry, I didn't encounter your error actually.

Can you provide more detail about your build step?

**Comment by juliusfrost** [comment]
I'm sorry, I am new to this, what do you mean by build step?

**Comment by fo40225** [comment]
what is your environment (hardware spec, software version, etc OS, visual studio, cuda, cudnn, python... )?
what command you type?
what action you do?

**Comment by fo40225** [comment]
It should work, but I don't know if both vs2015 and 2017 installed is the problem or not.

**Comment by fo40225** [comment]
@juliusfrost Try to enable "Developer Mode" in Win10 or use administrator privileges' cmd.

**Comment by wzlu** [comment]
@juliusfrost  Do you resolve it? I have the same problem...
