### ISSUE TITLE
Installation issue: zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by rahullak** [fo40225/tensorflow-windows-wheel#60]
First of all, thank you for providing the wheel files.

My issue is during installation. I have tried both **pip** and **wheel** and both give me the same error. Both were run in command-line with Administrator permissions. 

tensorflow-1.9.0-cp36-cp36m-win_amd64.whl

C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\pep425tags.py:77: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\pep425tags.py:81: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
Traceback (most recent call last):
  File "C:\Users\Rahul\Anaconda3\Scripts\wheel-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\tool\__init__.py", line 356, in main
    args.func(args)
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\tool\__init__.py", line 299, in install_f
    args.wheel_dirs, args.force, args.list_files)
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\tool\__init__.py", line 221, in install
    wf.install(force=force)
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\install.py", line 268, in install
    if self.parsed_wheel_info['Root-Is-Purelib'] == 'true':
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\decorator.py", line 17, in __get__
    val = self.wrapped(inst)
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\install.py", line 238, in parsed_wheel_info
    return read_pkg_info_bytes(self.zipfile.read(self.wheelinfo_name))
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\decorator.py", line 17, in __get__
    val = self.wrapped(inst)
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\install.py", line 230, in zipfile
    vzf = VerifyingZipFile(self.fp if self.fp else self.filename, mode)
  File "C:\Users\Rahul\Anaconda3\lib\site-packages\wheel\install.py", line 421, in __init__
    zipfile.ZipFile.__init__(self, file, mode, compression, allowZip64)
  File "C:\Users\Rahul\Anaconda3\lib\zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "C:\Users\Rahul\Anaconda3\lib\zipfile.py", line 1168, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

I get the same error with other versions of the .whl files as well.

Please help me. Much appreciated.

Thanks,

Rahul

**Comment by fo40225** [comment]
https://github.com/fo40225/tensorflow-windows-wheel/issues/13#issuecomment-390405684
