### ISSUE TITLE
tensorflow-1.13.1-cp37-cp37m-win_amd64.whl still errors

### ISSUE THREAD

**Issue by cyrilthank** [fo40225/tensorflow-windows-wheel#86]
below error still encountered 
on below 
#platform

windows 10
VisualStudion 16.1.3
conda
anaconda                  2019.03                  py37_0
python 3.7.3

#after

pip install --ignore-installed --upgrade  tensorflow-1.13.1-cp37-cp37m-win_amd64.whl

Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by fo40225** [comment]
@cyrilthank 
What is your CPU model?
Which whl file did you installed?

**Comment by cyrilthank** [comment]
@fo40225
Thank you for your response  sorry I think i downloaded from the folder avx2 instead of the sse2

**Comment by Bleach665** [comment]
I have same trouble.
Win 10 x64, Python 3.7.3, CUDA 10.1, VS 15.9.11.
CPU - i5 750, GPU - GT 730.
Tensorflow was installed to virtual environment by
`pip install --ignore-installed --upgrade tensorflow_gpu-1.13.1-cp37-cp37m-win_amd64.whl`

Error messages when importing TF:
````
(tf) E:\0\TF>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "E:\0\TF\tf\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "E:\0\TF\tf\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\0\TF\tf\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "E:\0\TF\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "E:\0\TF\tf\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "E:\0\TF\tf\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
````

**Comment by Bleach665** [comment]
@cyrilthank, the problem is the same as in this issue, therefore I dont open a new one. Can you look, please.

**Comment by cyrilthank** [comment]
Basically I was trying this in an older laptop with cpu which does not support avs

And instead of downloading the sse I downloaded avs2 

So once I downloaded the file from the ss* folder I was able to get past this

Thank you

Cyri
--------------------------------------------
On Fri, 7/5/19, Bleach665 <notifications@github.com> wrote:

 Subject: Re: [fo40225/tensorflow-windows-wheel] tensorflow-1.13.1-cp37-cp37m-win_amd64.whl still errors (#86)
 To: "fo40225/tensorflow-windows-wheel" <tensorflow-windows-wheel@noreply.github.com>
 Cc: "cyrilthank" <cyril_thank@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Friday, July 5, 2019, 11:09 PM
 
 @cyrilthank, the
 problem is the same as in this issue, therefore I dont open
 a new one. Can you look, please.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
